// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/user.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IUserServiceClient is the client API for IUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IUserServiceClient interface {
	Register(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error)
}

type iUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIUserServiceClient(cc grpc.ClientConnInterface) IUserServiceClient {
	return &iUserServiceClient{cc}
}

func (c *iUserServiceClient) Register(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error) {
	out := new(UserRegisterResponse)
	err := c.cc.Invoke(ctx, "/user.IUserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IUserServiceServer is the server API for IUserService service.
// All implementations must embed UnimplementedIUserServiceServer
// for forward compatibility
type IUserServiceServer interface {
	Register(context.Context, *UserRegisterRequest) (*UserRegisterResponse, error)
	mustEmbedUnimplementedIUserServiceServer()
}

// UnimplementedIUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIUserServiceServer struct {
}

func (UnimplementedIUserServiceServer) Register(context.Context, *UserRegisterRequest) (*UserRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedIUserServiceServer) mustEmbedUnimplementedIUserServiceServer() {}

// UnsafeIUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IUserServiceServer will
// result in compilation errors.
type UnsafeIUserServiceServer interface {
	mustEmbedUnimplementedIUserServiceServer()
}

func RegisterIUserServiceServer(s grpc.ServiceRegistrar, srv IUserServiceServer) {
	s.RegisterService(&IUserService_ServiceDesc, srv)
}

func _IUserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IUserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.IUserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IUserServiceServer).Register(ctx, req.(*UserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IUserService_ServiceDesc is the grpc.ServiceDesc for IUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.IUserService",
	HandlerType: (*IUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _IUserService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user.proto",
}
